# Generated by Django 4.1.6 on 2023-02-20 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=50)),
                ('recipe_image', models.ImageField(default='null.jpg', upload_to='sample')),
                ('instruction', models.CharField(max_length=100)),
                ('ingredients', models.CharField(max_length=100)),
            ],
        ),
    ]
